default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %> #solid cache configuration
    namespace: <%= Rails.env %>

development:
  database: cache
  <<: *default

test:
  <<: *default

production:
  database: cache
  <<: *default
  encrypt: true #solid cache configuration encryption